Process Process-2:
Process Process-4:
Process Process-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/g/gchen4/CT_NVAE/train.py", line 382, in init_processes
    fn(args)
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/g/gchen4/CT_NVAE/train.py", line 382, in init_processes
    fn(args)
  File "/global/homes/g/gchen4/CT_NVAE/train.py", line 38, in main
    train_queue, valid_queue, num_classes = datasets.get_loaders(args)
  File "/global/homes/g/gchen4/CT_NVAE/train.py", line 382, in init_processes
    fn(args)
  File "/global/homes/g/gchen4/CT_NVAE/train.py", line 38, in main
    train_queue, valid_queue, num_classes = datasets.get_loaders(args)
  File "/global/u1/g/gchen4/CT_NVAE/datasets.py", line 86, in get_loaders
    return get_loaders_eval(args.dataset, args)
  File "/global/homes/g/gchen4/CT_NVAE/train.py", line 38, in main
    train_queue, valid_queue, num_classes = datasets.get_loaders(args)
  File "/global/u1/g/gchen4/CT_NVAE/datasets.py", line 86, in get_loaders
    return get_loaders_eval(args.dataset, args)
  File "/global/u1/g/gchen4/CT_NVAE/datasets.py", line 177, in get_loaders_eval
    train_reconstruction = np.load(dataset_dir + '/dataset_foam/train_reconstructions.npy')
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
  File "/global/u1/g/gchen4/CT_NVAE/datasets.py", line 86, in get_loaders
    return get_loaders_eval(args.dataset, args)
  File "/global/u1/g/gchen4/CT_NVAE/datasets.py", line 177, in get_loaders_eval
    train_reconstruction = np.load(dataset_dir + '/dataset_foam/train_reconstructions.npy')
FileNotFoundError: [Errno 2] No such file or directory: '/dataset_foam/train_reconstructions.npy'
  File "/global/u1/g/gchen4/CT_NVAE/datasets.py", line 177, in get_loaders_eval
    train_reconstruction = np.load(dataset_dir + '/dataset_foam/train_reconstructions.npy')
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/dataset_foam/train_reconstructions.npy'
FileNotFoundError: [Errno 2] No such file or directory: '/dataset_foam/train_reconstructions.npy'
Process Process-1:
Traceback (most recent call last):
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/g/gchen4/CT_NVAE/train.py", line 382, in init_processes
    fn(args)
  File "/global/homes/g/gchen4/CT_NVAE/train.py", line 38, in main
    train_queue, valid_queue, num_classes = datasets.get_loaders(args)
  File "/global/u1/g/gchen4/CT_NVAE/datasets.py", line 86, in get_loaders
    return get_loaders_eval(args.dataset, args)
  File "/global/u1/g/gchen4/CT_NVAE/datasets.py", line 177, in get_loaders_eval
    train_reconstruction = np.load(dataset_dir + '/dataset_foam/train_reconstructions.npy')
  File "/global/homes/g/gchen4/.conda/envs/CT_NVAE/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/dataset_foam/train_reconstructions.npy'
